# Generated by Django 5.0.6 on 2024-05-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raso', '0002_rasovarity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasovarity',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
