# Generated by Django 5.0.6 on 2024-05-31 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raso', '0004_rasocertificate_rasoreview_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='loaction',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='RasoVarity',
            new_name='raso_varity',
        ),
    ]
